#include <WString.h>

String user = "admin";
String pass = "1234abcd";

String armaPaginaLogout(){
    String page = PSTR(
    "<!DOCTYPE HTML><html>"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">"
    "<link href=\"https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i\" rel=\"stylesheet\">"
    "<style type=\"text/css\">"
    "* *{"
        "margin: 0;"
        "padding: 0;"
        "box-sizing: border-box;"
        "font-family: 'Roboto', sans-serif;"
    "}"
    "body{"
        "background: #f1f1f1;"
    "}" 
    ".container{"
        "width: 100%;"
        "height: auto;"
        "padding: 5px;"
        "display: flex;"
        "justify-content: center;"
    "}"
    ".nodo-master-container{"
    "display: flex;"
    "width: auto;"
    "height: auto;"
    "background:#fff;"
    "box-shadow: 0 1px 1px 0 rgba(0, 0, 0, .2);"
    "}"
    ".register{"
        "padding: 20px;"
        "position: relative;"
    "}"
    ".register h2, .register h3 {"
        "color: #252222;"
        "margin-bottom: 20px;"
        "text-align: center;"
    "}"
    ".botonEsterilizar {"
        "width: 100%;"
        "height: 6vh;"
        "padding: 10px;"
        "background: #3b83bd!important;"
        "color: #fff!important;"
        "font-size: 14px;"
        "margin-bottom: 20px;"
        "box-shadow: 0 0 3px 0 rgba(0, 0, 0, .2);"
        "cursor: pointer;"
        "border: none;"
    "}"
    "</style>"

    "</head>"
    "<body>"
    "<div class=\"container\">"
    "<div class=\"nodo-master-container\">"
    "<div class=\"register\" style=\"width:380px\">"
        "<h2>Sesión Cerrada</h2>"
        //"<p>Logged out or <a href=\"/\">return to homepage</a>.</p>"
        // le quita lampara
        "<a href=\"/\"><button class=\"botonEsterilizar\">Ir a INICIO</button></a>"
        "<div><strong>Note:</strong> Cerrar todas las pestañas del navegador web para completar el proceso de cierre de sesión.</div>"
    "</div></div></div>"
    "</body>"
    "</html>");

    return page;
}